//
//  CloudLogicAPIFactory.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.18
//

import Foundation
import AWSCore

class CloudLogicAPIFactory {
    static var supportedCloudLogicAPIs: [CloudLogicAPI] {
        
        return [
            CloudLogicAPI(displayName: "WheelsTest",
                apiDescription: "Test api for wheels app",
                paths: [
                 "/items", "/items/123",                ],
                endPoint: "https://3pkfks1rqc.execute-api.us-west-2.amazonaws.com/Development",
                apiClient: AWSAPI_3PKFKS1RQC_WheelsTestMobileHubClient(forKey: AWSCloudLogicDefaultConfigurationKey)
            ),
            CloudLogicAPI(displayName: "locationsTest",
                apiDescription: "Created by AWS Lambda",
                paths: [
                 "/locationTest",                ],
                endPoint: "https://m8k6ozao1d.execute-api.us-west-2.amazonaws.com/prod",
                apiClient: AWSAPI_M8K6OZAO1D_LocationsTestClient(forKey: AWSCloudLogicDefaultConfigurationKey)
            ),
            CloudLogicAPI(displayName: "locationTestv2",
                apiDescription: "second test",
                paths: [
                 "/locationTestv2", "/locationTestv2/123",                ],
                endPoint: "https://8op0mvgrmg.execute-api.us-west-2.amazonaws.com/Development",
                apiClient: AWSAPI_8OP0MVGRMG_LocationTestvMobileHubClient(forKey: AWSCloudLogicDefaultConfigurationKey)
            ),
        ]
    }
}
